# Generated by Django 3.2.9 on 2021-11-27 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=30)),
                ('DOB', models.DateField(blank=True, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('mobile_number', models.CharField(max_length=14)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('created_date', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='temp_user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(max_length=14)),
                ('otp', models.CharField(max_length=6)),
                ('expiry_time', models.TimeField()),
                ('create_time', models.TimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='trade_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trade_id', models.IntegerField()),
                ('trade_type', models.CharField(max_length=50)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='tradesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tradesman_name', models.CharField(max_length=30)),
                ('created_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=20)),
                ('trade_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tradesman_trade_type', to='myapp.trade_type')),
            ],
        ),
        migrations.CreateModel(
            name='image_upload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/')),
                ('created_date', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_image', to='myapp.customer')),
            ],
        ),
        migrations.CreateModel(
            name='book_tradesman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('booked', 'Booked'), ('canceled', 'Canceled')], max_length=40)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_tradesman_customer', to='myapp.customer')),
                ('tradesman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.tradesman')),
            ],
        ),
    ]
